# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_88a7k_wmm1\clone\recipe, last modified Thu May 25 14:01:13 2023
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.8.0
source:
  sha256: 5e5212153e285a48223c70ede741d00304725a11cb690c494464a12f04c607f5
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.8.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_88a7k_wmm1\\croot\\conda-package-streaming_1685019697115\\_h_env\\python.exe
    -m pip install --no-deps --no-build-isolation . -vv
  string: py310haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - flit-core 3.8.0 py310haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 1.1.1t h2bbff1b_0
    - pip 23.0.1 py310haa95532_0
    - python 3.10.11 h966fe2a_2
    - setuptools 66.0.0 py310haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py310haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.10,<3.11.0a0
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming
    - conda_package_streaming.url
  requires:
    - pip
    - requests
about:
  description: 'An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.

    '
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8884296a-d557-4daf-9927-22739a477a79
  recipe-maintainers:
    - dholth
  remote_url: git@github.com:AnacondaRecipes/conda-package-streaming-feedstock.git
  sha: c97bb0d2ca70ce821af058e1d681f2602a352ce5
