# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_4b1rrw8pn9\clone\recipe, last modified Wed Oct 26 18:06:02 2022
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.4
source:
  sha256: 79ffa99156810e58876dd6374af0b7bff88f9a4580ca8b8468c414c5c2454bb8
  url: https://github.com/conda/pycosat/archive/0.6.4.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_4b1rrw8pn9\\croot\\pycosat_1666807711599\\_h_env\\python.exe
    -m pip install . --no-deps -vv
  string: py310h2bbff1b_0
requirements:
  build:
    - certifi 2022.9.24 py37haa95532_0
    - pip 22.2.2 py37haa95532_0
    - python 3.7.1 h33f27b4_4
    - setuptools 63.4.1 py37haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py37haa95532_2
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.07.19 haa95532_0
    - certifi 2022.9.24 py310haa95532_0
    - libffi 3.4.2 hd77b12b_4
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.2.2 py310haa95532_0
    - python 3.10.6 hbb2ffb3_1
    - setuptools 63.4.1 py310haa95532_0
    - sqlite 3.39.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022e h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.10,<3.11.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - python test_package.py "0.6.4"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  doc_url: https://pypi.org/project/pycosat/
  home: https://github.com/conda/pycosat
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  license_url: https://github.com/conda/pycosat/blob/0.6.4/LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4b82119d-49bf-4f8d-aafb-4ea7b00c606a
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - nehaljwani
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pycosat-feedstock.git
  sha: 18eedcf1f31f03a7e1ac629331f92a182cb57adb
