# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_fcga8w0uem\clone\recipe, last modified Wed Jan  4 20:43:31 2023
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 2.0.2
source:
  sha256: ec0a2c51f442d98b935ee2288beb1ec6c7e25020b5961f8d09f35738b276b532
  url: https://github.com/conda/conda-package-handling/archive/2.0.2.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  number: '0'
  script: C:\\b\\abs_fcga8w0uem\\croot\\conda-package-handling_1672865024290\\_h_env\\python.exe
    -m pip install . --no-deps -vv
  string: py310haa95532_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.10.11 haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - python 3.10.8 h966fe2a_1
    - sqlite 3.40.0 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.2.8 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.12.7 py310haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.3.1 py310haa95532_0
    - python 3.10.8 h966fe2a_1
    - setuptools 65.5.0 py310haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.8 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - conda-package-streaming >=0.7.0
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
    - pytest -v --cov=conda_package_handling --color=yes tests/
  imports:
    - conda_package_handling
    - conda_package_handling.api
  requires:
    - mock
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests
  source_files:
    - tests
about:
  description: 'cph is an abstraction of conda package handling and a tool for extracting,
    creating, and converting between formats.

    '
  dev_url: https://github.com/conda/conda-package-handling
  doc_source_url: https://github.com/conda/conda-package-handling/tree/2.0.2/docs
  doc_url: https://conda.github.io/conda-package-handling/
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  license_url: https://github.com/conda/conda-package-handling/blob/2.0.2/LICENSE
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: fc72733a-87b4-4a74-bde8-165198a54d9f
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
  remote_url: git@github.com:AnacondaRecipes/conda-package-handling-feedstock.git
  sha: 6ba36706a931d4d26e6e4c76759a38caef44d100
