# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_8ecplyc3n2\clone\recipe, last modified Mon Feb 27 21:24:40 2023
# ------------------------------------------------

package:
  name: cryptography
  version: 39.0.1
source:
  sha256: d1f6198ee6d9148405e49887803907fe8962a23e6c6f83ea7d98f1c0de375695
  url: https://pypi.io/packages/source/c/cryptography/cryptography-39.0.1.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_8ecplyc3n2\\croot\\cryptography_1677533105000\\_h_env\\python.exe
    -m pip install . -vv --no-deps
  string: py310h21b164f_0
requirements:
  build:
    - rust 1.64.0 haa95532_0
    - rust_win-64 1.46.0 hd77b12b_0
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py310haa95532_0
    - cffi 1.15.1 py310h2bbff1b_3
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py310haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.10.9 h966fe2a_0
    - semantic_version 2.8.5 pyhd3eb1b0_0
    - setuptools 65.6.3 py310haa95532_0
    - setuptools-rust 1.5.2 py310haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - typing_extensions 4.4.0 py310haa95532_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py310haa95532_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - cffi >=1.12
    - openssl
    - python >=3.10,<3.11.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - pytest -n auto
  requires:
    - cryptography-vectors 39.0.1.*
    - hypothesis >=1.11.4,!=3.79.2
    - iso8601
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-subtests
    - pytest-xdist
    - pytz
  source_files:
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/en/39.0.1/
  home: https://github.com/pyca/cryptography
  license: (BSD-3-Clause OR Apache-2.0) AND PSF-2.0 AND MIT
  license_family: BSD
  license_url: https://github.com/pyca/cryptography/blob/39.0.1/vectors/LICENSE
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8e4058cd-22b5-4dde-b9dc-b4a8b40422a6
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: f53e52003550a2e49f6d1cb2fda2a4124c75dba7
