# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\Users\builder\adipietro\aggregate\brotlipy-feedstock\recipe, last modified Thu Jan 13 06:16:47 2022
# ------------------------------------------------

package:
  name: brotlipy
  version: 0.7.0
source:
  fn: brotlipy-0.7.0.tar.gz
  sha256: 36def0b859beaf21910157b4c33eb3b06d8ce459c942102f16988cca6ea164df
  url: https://pypi.io/packages/source/b/brotlipy/brotlipy-0.7.0.tar.gz
build:
  number: '1002'
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: py310h2bbff1b_1002
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2021.10.26 haa95532_2
    - certifi 2021.5.30 py310haa95532_0
    - cffi 1.15.0 py310h2bbff1b_0
    - libffi 3.4.2 h604cdb4_1
    - openssl 1.1.1m h2bbff1b_0
    - pip 21.2.4 py310haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.10.0 h96c0403_3
    - setuptools 58.0.4 py310haa95532_0
    - sqlite 3.37.0 h2bbff1b_0
    - tk 8.6.11 h2bbff1b_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.5 h62dcd97_0
    - zlib 1.2.11 h8cc25b3_4
  run:
    - cffi >=1.0.0
    - python >=3.10,<3.11.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  imports:
    - brotli
about:
  dev_url: https://github.com/python-hyper/brotlipy
  home: https://github.com/python-hyper/brotlipy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings to the Brotli compression library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - astaric
    - isuruf
    - primozgodec
