# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_a8i949o_jm\clone\recipe, last modified Thu Jan  5 16:44:58 2023
# ------------------------------------------------

package:
  name: setuptools
  version: 65.6.3
source:
  patches:
    - patches/0002-disable-downloads-inside-conda-build.patch
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
  sha256: a7620757bf984b58deaf32fc8a4577a9bbc0850cf92c20e1ce41c38c19e5fb75
  url: https://pypi.io/packages/source/s/setuptools/setuptools-65.6.3.tar.gz
build:
  number: '0'
  string: py310haa95532_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.12.7 py310haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - python 3.10.8 h966fe2a_1
    - sqlite 3.40.0 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.8 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - certifi >=2016.9.26
    - python >=3.10,<3.11.0a0
    - wincertstore >=0.2
test:
  commands:
    - pip check
  imports:
    - pkg_resources
    - setuptools
  requires:
    - pip
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/main/docs
  doc_url: https://setuptools.pypa.io/en/latest/
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/pypa/setuptools/blob/main/LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a821bbb5-5696-4344-9a6f-a7ba4f6bd952
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - nicoddemus
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/setuptools-feedstock.git
  sha: f5d8d256810ce28fc0cf34170bc34e06d3754041
