# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_57pucx8qdr\clone\recipe, last modified Fri Feb 17 08:17:05 2023
# ------------------------------------------------

package:
  name: wheel
  version: 0.38.4
source:
  sha256: 965f5259b566725405b05e7cf774052044b1ed30119b5d586b2703aafe8719ac
  url: https://pypi.io/packages/source/w/wheel/wheel-0.38.4.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  number: '0'
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: py310haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py310haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - python 3.10.9 h966fe2a_0
    - setuptools 65.6.3 py310haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
    - wheel --help
    - wheel version
  imports:
    - wheel
    - wheel.cli
    - wheel.vendored
    - wheel.vendored.packaging
  requires:
    - pip
about:
  description: "This library is the reference implementation of the Python wheel packaging\
    \ standard,\nas defined in PEP 427.\nIt has two different roles:\n  1. A setuptools\
    \ extension for building wheels that provides the bdist_wheel setuptools command\n\
    \  2. A command line tool for working with wheel files\n"
  dev_url: https://github.com/pypa/wheel
  doc_url: https://wheel.readthedocs.io/
  home: https://github.com/pypa/wheel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 576375c1-7d93-47a1-a62a-588d81bf2d54
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/wheel-feedstock.git
  sha: 3a6887d038d3c92954c0adff1039216772e1fd18
  skip-lints:
    - missing_wheel
    - uses_setup_py
