# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_c0slxgja41\clone\recipe, last modified Tue Feb 21 21:29:26 2023
# ------------------------------------------------

package:
  name: zstandard
  version: 0.19.0
source:
  sha256: 31d12fcd942dd8dbf52ca5f6b1bbe287f44e5d551a081a983ff3ea2082867863
  url: https://pypi.io/packages/source/z/zstandard/zstandard-0.19.0.tar.gz
build:
  number: '0'
  string: py310h2bbff1b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py310haa95532_0
    - cffi 1.15.1 py310h2bbff1b_3
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py310haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.10.9 h966fe2a_0
    - setuptools 65.6.3 py310haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py310haa95532_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - cffi >=1.11
    - python >=3.10,<3.11.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/main/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - zstd/LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: c00ad9a9-28a3-4c9d-8a01-40421ca26278
  recipe-maintainers:
    - rmax
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/zstandard-feedstock.git
  sha: 99a78902d32478ec461b8712d9ef1d911904a19f
