# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\Users\builder\adipietro\aggregate\pysocks-feedstock\recipe, last modified Thu Jan 13 06:23:20 2022
# ------------------------------------------------

package:
  name: pysocks
  version: 1.7.1
source:
  sha256: 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
  url: https://pypi.io/packages/source/P/PySocks/PySocks-1.7.1.tar.gz
build:
  number: '0'
  script: C:\ci_310\pysocks_1642089375450\_h_env\python.exe -m pip install . --no-deps
    -vv
  string: py310haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2021.10.26 haa95532_2
    - certifi 2021.5.30 py310haa95532_0
    - libffi 3.4.2 h604cdb4_1
    - openssl 1.1.1m h2bbff1b_0
    - pip 21.2.4 py310haa95532_0
    - python 3.10.0 h96c0403_3
    - setuptools 58.0.4 py310haa95532_0
    - sqlite 3.37.0 h2bbff1b_0
    - tk 8.6.11 h2bbff1b_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.5 h62dcd97_0
    - zlib 1.2.11 h8cc25b3_4
  run:
    - python >=3.10,<3.11.0a0
    - win_inet_pton
test:
  imports:
    - socks
about:
  dev_url: https://github.com/Anorov/PySocks
  doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
  home: https://github.com/Anorov/PySocks
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
    more information.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
