#!E:\GitHub_pro\AI-Vtuber-20240702\Miniconda3\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
