# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_82o683t8to\clone\recipe, last modified Tue Mar  7 10:36:54 2023
# ------------------------------------------------

package:
  name: pip
  version: 23.0.1
source:
  sha256: cd015ea1bfb0fcef59d8a286c1f8bebcb983f6317719d415dc5351efb7cd7024
  url: https://pypi.io/packages/source/p/pip/pip-23.0.1.tar.gz
build:
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  number: '0'
  string: py310haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py310haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - python 3.10.9 h966fe2a_1
    - setuptools 65.6.3 py310haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py310haa95532_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.10,<3.11.0a0
    - setuptools
    - wheel
test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip
about:
  dev_url: https://github.com/pypa/pip
  doc_url: https://pip.pypa.io/en/stable/
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 821b97fa-9171-46c2-b3fb-2b461800f601
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pip-feedstock.git
  sha: 6552ed008e00cec1105d280c8cb80c94aa12375b
