# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\Windows\TEMP\abs_4589313d-fc62-4ccc-81c0-b801b4449e833j1ajrwu\clone\recipe, last modified Mon Jul 18 06:39:32 2022
# ------------------------------------------------

package:
  name: conda-content-trust
  version: 0.1.3
source:
  fn: conda-content-trust-0.1.3.tar.gz
  sha256: 50a2732dcf3612bdff2b36171e3ebc72a74bbc258543a5aa2618218406b30a0d
  url: https://github.com/conda/conda-content-trust/archive/0.1.3.tar.gz
build:
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli
  number: '0'
  script: C:\\Windows\\TEMP\\abs_4589313d-fc62-4ccc-81c0-b801b4449e833j1ajrwu\\croots\\recipe\\conda-content-trust_1658126379362\\_h_env\\python.exe
    -m pip install --no-deps --ignore-installed -vv .
  string: py310haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.4.26 haa95532_0
    - certifi 2022.6.15 py310haa95532_0
    - libffi 3.4.2 hd77b12b_4
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.1.2 py310haa95532_0
    - python 3.10.4 hbb2ffb3_0
    - setuptools 61.2.0 py310haa95532_0
    - sqlite 3.38.5 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_2
  run:
    - cryptography
    - python >=3.10,<3.11.0a0
    - six
test:
  commands:
    - pip check
    - pytest -v tests
    - conda-content-trust --help
  imports:
    - conda_content_trust
  requires:
    - pip
    - pytest
    - pytest-cov
    - ruamel_yaml
  source_files:
    - tests
about:
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.rst
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4589313d-fc62-4ccc-81c0-b801b4449e83
  remote_url: git@github.com:AnacondaRecipes/conda-content-trust-feedstock.git
  sha: 4e69a87949a2597071655306e4ed8c062ddd8518
