# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# C:\ci\containers\00001gi8kla\tmp\build\80754af9\rsync-recipes\wincertstore-0.2-python_3.10-on-winbuilder, last modified Thu Sep 30 11:19:02 2021
# ------------------------------------------------

package:
  name: wincertstore
  version: '0.2'
source:
  fn: wincertstore-0.2.zip
  sha256: 780bd1557c9185c15d9f4221ea7f905cb20b93f7151ca8ccaed9714dce4b327a
  url: https://pypi.io/packages/source/w/wincertstore/wincertstore-0.2.zip
build:
  number: '2'
  script: C:\\ci\\wincertstore_1633019021897\\_h_env\\python.exe setup.py install
  string: py310haa95532_2
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2021.7.5 haa95532_1
    - libffi 3.4.2 hd77b12b_0
    - openssl 1.1.1l h2bbff1b_0
    - python 3.10.0rc2 hbb2ffb3_0
    - sqlite 3.36.0 h2bbff1b_0
    - tk 8.6.11 h2bbff1b_0
    - tzdata 2021a h5d7bf9c_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.2.5 h62dcd97_0
    - zlib 1.2.11 h62dcd97_4
  run:
    - python >=3.10,<3.11.0a0
test:
  imports:
    - wincertstore
about:
  home: https://bitbucket.org/tiran/wincertstore
  license: PSF 2
  license_file: LICENSE
  summary: Python module to extract CA and CRL certs from Windows' cert store (ctypes
    based).
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - patricksnape
