# This file created by conda-build 3.23.1
# meta.yaml template originally from:
# C:\b\abs_49n3v2hyhr\clone\recipe, last modified Wed Dec  7 14:26:46 2022
# ------------------------------------------------

package:
  name: cffi
  version: 1.15.1
source:
  patches:
    - 0001-Link-to-dl-library.patch
  sha256: d400bfb9a37b1351253cb402671cea7e89bdecc294e8016a707f6d1d8ac934f9
  url: https://pypi.io/packages/source/c/cffi/cffi-1.15.1.tar.gz
build:
  missing_dso_whitelist: null
  number: '3'
  script: C:\\b\\abs_49n3v2hyhr\\croot\\cffi_1670423218144\\_h_env\\python.exe -m
    pip install . --no-deps -vv
  string: py310h2bbff1b_3
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py310haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.2.2 py310haa95532_0
    - python 3.10.8 h966fe2a_1
    - setuptools 65.5.0 py310haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.8 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - pycparser
    - python >=3.10,<3.11.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - _cffi_backend
    - cffi
  requires:
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://foss.heptapod.net/pypy/cffi
  doc_source_url: https://foss.heptapod.net/pypy/cffi/-/tree/branch/default/doc/source
  doc_url: https://cffi.readthedocs.io/en/latest/
  home: https://cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 498d4df6-d43f-41c2-8750-2ca5b21219e2
  recipe-maintainers:
    - goanpeca
    - inducer
    - mingwandroid
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cffi-feedstock.git
  sha: 1d0b98bd6262574564cad512fac5e0fe6e1df9ad
