# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_41owkd5ymz\clone\recipe, last modified Thu Apr 27 15:58:32 2023
# ------------------------------------------------

package:
  name: requests
  version: 2.29.0
source:
  sha256: f2e34a75f4749019bb0e3effb66683630e4ffeaf75819fb51bebef1bf5aef059
  url: https://pypi.io/packages/source/r/requests/requests-2.29.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_41owkd5ymz\\croot\\requests_1682607524657\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py310haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 23.0.1 py310haa95532_0
    - python 3.10.11 h966fe2a_2
    - setuptools 66.0.0 py310haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py310haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - python >=3.10,<3.11.0a0
    - urllib3 >=1.21.1,<1.27
  run_constrained:
    - chardet >=3.0.2,<6
test:
  commands:
    - pip check
    - conda create -v --dry-run -n requests-test numpy
  imports:
    - requests
  requires:
    - conda
    - pip
about:
  description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

    consumption.

    '
  dev_url: https://github.com/psf/requests
  doc_url: https://requests.readthedocs.io/en/latest/
  home: https://requests.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 41ddb0ea-d64e-4709-9410-cd3c27f520ed
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/requests-feedstock.git
  sha: 10299c7ae57ca50f3222f74f1330bd22cea15b3f
