#!/bin/sh
_CONDA_ROOT="C:\b\abs_e85v4h503s\croot\conda_1680188135976\_h_env"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
