# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_ed_kb9w6g4\clone\recipe, last modified Thu Mar 16 12:16:45 2023
# ------------------------------------------------

package:
  name: packaging
  version: '23.0'
source:
  sha256: b6ad297f8907de0fa2fe1ccbd26fdaf387f5f47c7275fedf8cce89f99446cf97
  url: https://pypi.io/packages/source/p/packaging/packaging-23.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_ed_kb9w6g4\\croot\\packaging_1678965418855\\_h_env\\python.exe
    -m pip install . --no-deps -vv
  string: py310haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py310haa95532_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 23.0.1 py310haa95532_0
    - python 3.10.9 h966fe2a_2
    - setuptools 65.6.3 py310haa95532_0
    - sqlite 3.41.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py310haa95532_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
  imports:
    - packaging
  requires:
    - pip
about:
  dev_url: https://github.com/pypa/packaging
  doc_source_url: https://github.com/pypa/packaging/tree/main/docs
  doc_url: https://packaging.pypa.io
  home: https://github.com/pypa/packaging
  license: Apache-2.0 or BSD-2-Clause
  license_family: Apache
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: edaa2abc-dd5d-44e8-8517-5aa1a7e1e024
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/packaging-feedstock.git
  sha: a525d3ca60583c6131c37d030c19e8fc9b0b11a9
