# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\ci\containers\00001dnr6c5\tmp\build\80754af9\rsync-recipes\pluggy-1.0.0-python_3.10-on-winbuilder, last modified Wed Mar 23 08:25:41 2022
# ------------------------------------------------

package:
  name: pluggy
  version: 1.0.0
source:
  fn: pluggy-1.0.0.tar.gz
  sha256: 4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159
  url: https://pypi.io/packages/source/p/pluggy/pluggy-1.0.0.tar.gz
build:
  number: '1'
  script: python -m pip install . --no-deps --ignore-installed
  string: py310haa95532_1
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.2.1 haa95532_0
    - certifi 2021.5.30 py310haa95532_0
    - libffi 3.4.2 h604cdb4_1
    - openssl 1.1.1n h2bbff1b_0
    - packaging 21.3 pyhd3eb1b0_0
    - pip 21.2.4 py310haa95532_0
    - pyparsing 3.0.4 pyhd3eb1b0_0
    - python 3.10.0 h96c0403_3
    - setuptools 58.0.4 py310haa95532_0
    - setuptools-scm 6.3.2 pyhd3eb1b0_0
    - setuptools_scm 6.3.2 hd3eb1b0_0
    - sqlite 3.38.0 h2bbff1b_0
    - tk 8.6.11 h2bbff1b_0
    - tomli 1.2.2 pyhd3eb1b0_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.5 h62dcd97_0
    - zlib 1.2.11 hbd8134f_5
  run:
    - python >=3.10,<3.11.0a0
test:
  command:
    - pip check
  imports:
    - pluggy
  requires:
    - pip
about:
  dev_url: https://github.com/pytest-dev/pluggy/
  doc_url: https://pluggy.readthedocs.io/en/latest/
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohnGreeley
    - nicoddemus
