# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_ce4_vcfd0y\clone\recipe, last modified Thu May 25 15:26:25 2023
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 2.1.0
source:
  sha256: dcaa757fca94857420acd21b27d1ff6939e34522d196c3bafdd6dfed90559da5
  url: https://github.com/conda/conda-package-handling/archive/2.1.0.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  number: '0'
  script: C:\\b\\abs_ce4_vcfd0y\\croot\\conda-package-handling_1685024800103\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py310haa95532_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 1.1.1t h2bbff1b_0
    - python 3.10.11 h966fe2a_2
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 1.1.1t h2bbff1b_0
    - pip 23.0.1 py310haa95532_0
    - python 3.10.11 h966fe2a_2
    - setuptools 66.0.0 py310haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py310haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - conda-package-streaming >=0.7.0
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
    - pytest -v --cov=conda_package_handling --color=yes tests/
  imports:
    - conda_package_handling
    - conda_package_handling.api
  requires:
    - mock
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests
  source_files:
    - tests
about:
  description: 'cph is an abstraction of conda package handling and a tool for extracting,
    creating, and converting between formats.

    '
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ce136aa3-387e-4919-ad55-7510febffa20
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
  remote_url: git@github.com:AnacondaRecipes/conda-package-handling-feedstock.git
  sha: 2b63d384832da870e100eb74d65b322c3bb1fe2d
