# This file created by conda-build 3.23.1
# meta.yaml template originally from:
# C:\b\abs_0e5n5hdal3\clone\recipe, last modified Thu Dec  8 14:02:29 2022
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.7.0
source:
  sha256: 87be2b1c365a0e04d15579b9137b139f0837c52198bdba21c5ac071fc13efd75
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.7.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_0e5n5hdal3\\croot\\conda-package-streaming_1670508162902\\_h_env\\python.exe
    -m pip install --no-build-isolation . -vv
  string: py310haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py310haa95532_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.2.2 py310haa95532_0
    - python 3.10.8 h966fe2a_1
    - setuptools 65.5.0 py310haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.8 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.10,<3.11.0a0
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming
    - conda_package_streaming.url
  requires:
    - pip
    - requests
about:
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0eb46d5b-5e9b-43d8-8c87-50cace5c0d72
  recipe-maintainers:
    - dholth
  remote_url: git@github.com:AnacondaRecipes/conda-package-streaming-feedstock.git
  sha: 0d6428f0165f2fa2fd2de24ce50216dc442be5d8
